Maven project with JUnit
IrinaBogatko95/TAT-2016-1 pull request #15
Opened 2016-10-30 05:41 UTC by IrinaBogatko95

2016-10-30 20:20 UTC, AlexanderSoroka requested changes

2016-10-30 20:20 UTC, AlexanderSoroka commented on Task_11_Test/src/main/java/Movement/CarTrip.java
> +        return 1000 * time / 1000;
1000 * time / 1000 - does it just equal to time?

2016-10-30 20:20 UTC, AlexanderSoroka commented on Task_11_Test/src/main/java/Movement/GetCheckpoints.java
> +            BufferedReader br = new BufferedReader(new FileReader("E:\\points.txt"));
do not use hardcoded paths in the code - pass it as method argument

2016-10-30 20:20 UTC, AlexanderSoroka commented on Task_11_Test/src/test/java/Movement/BicycleTripTest.java
> +        assertNotEquals(-143, time);
does it mean -142 would be ok?

2016-10-30 20:20 UTC, AlexanderSoroka commented on Task_11_Test/src/test/java/Movement/DistanceTest.java
> +        assertNotEquals(-60, distance.getDistance(checkpoints));
I suppose -59 is ok. Please comment why you decided to use NotEquals here in so strange manner

2016-10-31 10:04 UTC, IrinaBogatko95 commented on Task_11_Test/src/test/java/Movement/DistanceTest.java
> +        assertNotEquals(-60, distance.getDistance(checkpoints));
You are right, this test is useless.

2016-11-04 08:02 UTC, merged